#!/bin/dash

# check if .shrug directory exists
if [ -e ".shrug" ]; then
    echo "shrug-init: error: .shrug already exists" >&2
    exit 1
else

    # else make .shrug directory with index inside
    mkdir .shrug
    mkdir .shrug/index
    touch .shrug/COMMIT_HISTORY
    echo "Initialized empty shrug repository in .shrug"

fi
exit 0
